// Single source of truth for the cut. Renderer, score and SHOTLIST.md all read this.
// dur in seconds. focus = x (0..1) of the subject, used for the square crop.
const SHOTS = [
  { id: 'S01', dur: 6.0, ch: 'open', name: 'The cupboard',
    desc: 'Hall cupboard in the dark. A thin blade of light from the door crack lies across the brass telescope; dust turns in it; the light slides to the cracked eyepiece and catches the crack.',
    cam: 'Locked, very slow push-in (1.00 to 1.06)', chars: 'Telescope', beat: 'Hook. What is that?',
    audio: 'Room tone, a clock in another room. One plucked phrase: four notes of the tune, unresolved.', focus: 0.52 },
  { id: 'S02', dur: 4.5, ch: 'open', name: 'Title',
    desc: '"After Work" writes itself on in warm cream over deep indigo. One star twinkles above the W.',
    cam: 'Locked', chars: '-', beat: 'Promise of something gentle',
    audio: 'Last note rings out; conveyor hum pre-laps under the last second.', focus: 0.5 },

  { id: 'S03', dur: 6.5, ch: 'work', name: 'The warehouse at 3am',
    desc: 'Low wide: conveyor running diagonally past camera, parcels sliding, sodium lamps in haze with dust in the cones. Nell small at the line, scanning. "2027" lettered small, lower left.',
    cam: 'Low (knee height), slow truck right', chars: 'Nell (49)', beat: 'The routine. Scale: she is small here.',
    audio: 'Conveyor hum, fluorescent buzz, rollers, distant scanner beeps, a cage rattling far off.', focus: 0.62 },
  { id: 'S04', dur: 5.0, ch: 'work', name: 'Her hands',
    desc: 'Close: her gloved hands take a parcel, scan (red line, beep), turn, place. Three parcels, quick and exact.',
    cam: 'Locked, top-down three-quarter', chars: 'Nell hands', beat: 'Dignity. She is good at this.',
    audio: 'Beep on each scan, cardboard slides, the rhythm of it.', focus: 0.5 },
  { id: 'S05', dur: 5.0, ch: 'work', name: 'Tired eyes',
    desc: 'Nell three-quarter face, lit orange from above, tired. She blinks slowly and her eyes lift toward the roof.',
    cam: 'Low, looking slightly up; locked', chars: 'Nell (49)', beat: 'Exhaustion, and a small wanting.',
    audio: 'Hum drops lower, as if we are inside her head.', focus: 0.45 },
  { id: 'S06', dur: 5.0, ch: 'work', name: 'The skylight',
    desc: 'POV up through a grimy wired skylight: grime, a dead leaf, one star through a clear patch. The star twinkles. Only the star moves.',
    cam: 'Locked, straight up', chars: '-', beat: 'Looking up. The first star.',
    audio: 'She hums the first four notes of the tune, barely, under the hum.', focus: 0.5 },
  { id: 'S07', dur: 4.0, ch: 'work', name: 'The time clock',
    desc: 'Close on the time clock: her card goes in, CLUNK, stamped 06:02. Grey-green dawn from the open door.',
    cam: 'Locked, eye level with the clock', chars: 'Nell hand', beat: 'End of shift. Time traded.',
    audio: 'The clunk. Door opening, early birds, the hum cut off.', focus: 0.5 },
  { id: 'S08', dur: 6.5, ch: 'work', name: 'Kitchen at dawn',
    desc: 'Her kitchen, eye level. Only the kettle steam moves. Then Nell sits into frame at the table in her coat and rests her head on her hand. Sam\'s crayon rocket on the fridge.',
    cam: 'Locked, eye level (the kitchen camera)', chars: 'Nell (49)', beat: 'Home. Stillness.',
    audio: 'Kettle rising, clicks off. Chair scrape. A blackbird outside.', focus: 0.55 },

  { id: 'S09', dur: 6.5, ch: 'work', name: 'The machines',
    desc: 'The warehouse, later. A row of new sorting arms: pale, rounded, each with a small amber lamp, working quietly. Nell walks along the line. The nearest arm pauses mid-motion to let her pass, then carries on.',
    cam: 'Low, locked', chars: 'Nell (49), sorting arms', beat: 'Unease without villainy. They are polite.',
    audio: 'The old hum thinner; a soft pneumatic rhythm; clean high beeps.', focus: 0.45 },
  { id: 'S10', dur: 5.0, ch: 'work', name: 'Match cut',
    desc: 'Same framing as S04. A gripper does her exact motion: take, scan, turn, place, twice as fast. Her gloved hand enters at the edge, hesitates, withdraws.',
    cam: 'Locked, identical to S04', chars: 'Gripper, Nell hand', beat: 'The replacement, shown fairly.',
    audio: 'Beeps at double tempo. Then just the machine.', focus: 0.5 },

  { id: 'S11', dur: 5.5, ch: 'fear', name: 'The letter',
    desc: 'Kitchen table, close. A hand-lettered letter in her hands: the new sorting line, her position ending on 30 November, thanks for eleven years.',
    cam: 'Locked, over the table', chars: 'Nell hands', beat: 'The stomach drop.',
    audio: 'Clock tick, fridge hum. No music.', focus: 0.5 },
  { id: 'S12', dur: 5.0, ch: 'fear', name: 'Her face',
    desc: 'Nell three-quarter, eye level, reading. Very still. Her hand comes up to her mouth.',
    cam: 'Locked, eye level', chars: 'Nell (49)', beat: 'Sit in it.',
    audio: 'Clock. Her breath.', focus: 0.45 },
  { id: 'S13', dur: 6.0, ch: 'fear', name: 'Sam in the doorway',
    desc: 'From the hall at a nine-year-old\'s height: the edge of the door frame, Sam half-hidden, and beyond him his mum\'s back small at the kitchen table. Rain starts on the window.',
    cam: 'Low (child height), locked', chars: 'Sam (9), Nell (49)', beat: 'The kid sees it.',
    audio: 'Rain begins on the window. A low single cello note under it.', focus: 0.35 },

  { id: 'S14', dur: 7.0, ch: 'winter', name: 'The street in winter',
    desc: 'Her street at dusk in snow, terraced houses, one streetlamp, a shuttered shop marked TO LET. Snow falls as individual lines. Nell walks home with a bag; her breath fogs. "2028" lettered small.',
    cam: 'Locked wide, eye level (the street camera)', chars: 'Nell (50)', beat: 'The hard middle.',
    audio: 'Winter wind, footsteps in snow. The tune in a minor key, low, slow.', focus: 0.4 },
  { id: 'S15', dur: 5.0, ch: 'winter', name: 'Sums',
    desc: 'The kitchen camera again, cold blue. Nell in her coat indoors doing sums in a notebook. Sam at the end of the table in a woolly hat doing homework. Frost on the window. The shelf is emptier.',
    cam: 'Locked, eye level (kitchen camera)', chars: 'Nell (50), Sam (10)', beat: 'It is hard.',
    audio: 'Wind at the window, pencil, a radiator tick that isn\'t on.', focus: 0.5 },
  { id: 'S16', dur: 5.5, ch: 'winter', name: 'The hall',
    desc: 'Night, snow. The community hall across the street, windows warm. Neighbours arriving with dishes. Nell and Sam hesitate at the door, then go in.',
    cam: 'Locked wide', chars: 'Nell, Sam, neighbours', beat: 'People gathering.',
    audio: 'Wind; the door opens and a warm murmur spills out.', focus: 0.5 },
  { id: 'S17', dur: 6.0, ch: 'winter', name: 'The noticeboard',
    desc: 'Inside, warm. A cork noticeboard of hand-lettered cards: bike repairs, childminding swaps, lifts to the hospital, "learning together, Thursdays 7pm". Tea urn steam at the edge.',
    cam: 'Slow pan right across the board', chars: '-', beat: 'Not alone. Figuring it out together.',
    audio: 'Crowd murmur, cups, one laugh.', focus: 0.5 },
  { id: 'S18', dur: 5.5, ch: 'winter', name: 'The second letter',
    desc: 'The kitchen table again, same framing as S11. A different letter: a payment to every household, every month. The hands steady. Low winter sun crosses the table: the thaw.',
    cam: 'Locked, identical to S11', chars: 'Nell hands', beat: 'The world adjusted. An exhale.',
    audio: 'Drip of thaw. A long breath out. The first warm chord since the title.', focus: 0.5 },

  { id: 'S19', dur: 6.0, ch: 'turn', name: 'The cupboard door',
    desc: 'The hall at night. The same thin blade of light, seen from outside now. Her hand on the cupboard. She opens it and light falls across the telescope.',
    cam: 'Locked, eye level, slight push', chars: 'Nell (51)', beat: 'The turn.',
    audio: 'Door creak. The four notes again, and this time a fifth.', focus: 0.5 },
  { id: 'S20', dur: 6.0, ch: 'turn', name: "Dad's note",
    desc: 'Morning gold. The case open on the kitchen table. A folded pencil note in the lid: "Nell. First clear night I\'m off, we\'ll find Saturn. Promise. Dad"',
    cam: 'Locked, over the table', chars: 'Nell hands', beat: 'The reveal begins.',
    audio: 'Paper unfolding. Birds. A held note.', focus: 0.64 },
  { id: 'S21', dur: 6.5, ch: 'memory', name: 'The memory',
    desc: 'Sepia. The back step at dusk, years ago. Her father in his work jacket pointing up; small Nell beside the telescope. He checks his watch, picks up his lunch tin, and goes. She stays.',
    cam: 'Locked, eye level', chars: 'Arthur (44), Nell (8)', beat: 'He traded his nights too.',
    audio: 'Her father hums the tune (lower). A door closes.', focus: 0.45 },
  { id: 'S22', dur: 8.0, ch: 'turn', name: 'Learning',
    desc: 'Kitchen table: a small warm light beside an open book. The pages fill with drawings: the sky, then lenses and light bending through glass. Pages turn one at a time. Window light changes through days; the plant grows.',
    cam: 'Locked, slightly above the table', chars: 'Nell hands, the warm light', beat: 'Absorption. The joy of figuring it out.',
    audio: 'Pages, pencil, birds. The tune as a plucked, curious ostinato.', focus: 0.5 },
  { id: 'S23', dur: 5.0, ch: 'turn', name: 'Fixing',
    desc: 'Hands: unscrewing the cracked eyepiece, fitting a new one, polishing brass. The dent stays. A glint runs down the tube.',
    cam: 'Locked, close', chars: 'Nell hands, telescope', beat: 'Care.',
    audio: 'Thread turning, a small click, cloth on brass.', focus: 0.5 },
  { id: 'S24', dur: 5.0, ch: 'night', name: 'The back step',
    desc: 'Night, early spring. Nell sets up the telescope on the back step. Sam (11) in his coat on the step. First stars.',
    cam: 'Eye level, tilting slightly up', chars: 'Nell (51), Sam (11)', beat: 'Anticipation.',
    audio: 'Night air, distant town, a dog far away.', focus: 0.5 },
  { id: 'S25', dur: 8.0, ch: 'night', name: 'Saturn',
    desc: 'Through the eyepiece: blur, drifting stars, and then Saturn slides in. Tiny, pale gold, rings clear, trembling in the air. It centres and holds.',
    cam: 'POV, circular field', chars: '-', beat: 'The moment.',
    audio: 'Silence, then the first full phrase of the tune on piano.', focus: 0.5 },
  { id: 'S26', dur: 6.5, ch: 'night', name: 'Her face',
    desc: 'Nell at the eyepiece, then pulling back. Wonder, wet eyes, a laugh breaking. She beckons Sam. He looks, and laughs out loud.',
    cam: 'Locked, eye level', chars: 'Nell (51), Sam (11)', beat: 'The promise kept.',
    audio: "Sam's laugh. The phrase resolves.", focus: 0.52 },

  { id: 'S27', dur: 5.0, ch: 'gold', name: 'Chalk on the step',
    desc: 'Day. Nell and Sam drawing Saturn and orbits in chalk on the back step. "2031".',
    cam: 'Top-down, locked', chars: 'Nell (53), Sam (13)', beat: 'Teaching begins at home.',
    audio: 'Chalk scratch, birds, a door open to the street.', focus: 0.5 },
  { id: 'S28', dur: 6.5, ch: 'gold', name: 'The rooftop',
    desc: 'A flat rooftop at golden hour. Neighbours on folding chairs. A small chalkboard with orbits. The telescope against the sun. Nell pointing up.',
    cam: 'Low, looking up; slow tilt up', chars: 'Nell (54), neighbours', beat: 'Sharing it.',
    audio: 'Murmur, chalk, swifts.', focus: 0.5 },
  { id: 'S29', dur: 9.0, ch: 'gold', name: 'The street, years',
    desc: 'The street camera again, locked. Held states through years: car park dug into garden beds; a workshop door open; benches; bunting; old and young; a hand-painted sign "Night school, all welcome". Same houses, more life.',
    cam: 'Locked, identical to S14', chars: 'Neighbours, Sam growing', beat: 'The world opening up.',
    audio: 'Children, birds, bicycle bell, a radio through a window.', focus: 0.5 },
  { id: 'S30', dur: 8.0, ch: 'gold', name: 'The kitchen clock',
    desc: 'The kitchen camera again. Held states: the shelves fill (books, a Saturn model, a jar of lenses, a fiddle, seedlings). Sam at the table at 14, 17, 22, learning something different each time. The warm light still there. Nell greying.',
    cam: 'Locked, identical to S08/S15', chars: 'Nell (54 to 62), Sam (14 to 22)', beat: 'Learning never finishes.',
    audio: 'A clock, gently. The tune\'s second half in fragments.', focus: 0.5 },
  { id: 'S31', dur: 6.5, ch: 'gold', name: 'The full room',
    desc: 'The community hall again, now full: every age. Nell (58) at a big chalkboard of the planets. A hand goes up.',
    cam: 'Low, looking up at the board', chars: 'Nell (58), the town', beat: 'Everyone has time now.',
    audio: 'Hush of a room listening, chalk, a chair creak.', focus: 0.5 },

  { id: 'S32', dur: 7.0, ch: 'end', name: 'The back step, 2047',
    desc: 'Night. Nell (69) in a chair under a blanket beside the telescope. Sam (29) and his daughter at the eyepiece. "2047". Crickets.',
    cam: 'Eye level, slow tilt up', chars: 'Nell (69), Sam (29), granddaughter (7)', beat: 'Full circle.',
    audio: 'Crickets. Nell hums the tune; the full score begins.', focus: 0.5 },
  { id: 'S33', dur: 8.5, ch: 'end', name: 'The launch',
    desc: 'Wide: rooftops in silhouette, indigo sky. On the horizon a thin bright line climbs slowly. Only the line moves, and one star.',
    cam: 'Locked, mostly sky', chars: '-', beat: 'Outward.',
    audio: 'Crickets, the tune. Nothing from the launch yet.', focus: 0.62 },
  { id: 'S34', dur: 6.5, ch: 'end', name: 'Her eyes',
    desc: 'Nell in profile, watching with her own eyes, the line reflected small in them. She smiles. The telescope creaks as the girl swings it. The rumble arrives late.',
    cam: 'Locked, eye level', chars: 'Nell (69)', beat: 'She does not need the telescope.',
    audio: 'The late rumble, low and soft. Creak of the tripod.', focus: 0.45 },
  { id: 'S35', dur: 14.0, ch: 'end', name: 'Pull back',
    desc: 'From the glint on the telescope lens, out: the back step, the house, the lit street, the town, the curve of the night planet, and out into space where small warm lights drift outward among the stars.',
    cam: 'Continuous pull back and up', chars: '-', beat: 'Not small, not alone.',
    audio: 'The tune in full, piano and strings, to the last note.', focus: 0.5 },
  { id: 'S36', dur: 5.0, ch: 'end', name: 'One line',
    desc: 'Held stars. One line lettered small: "For everyone who ever worked nights."',
    cam: 'Locked', chars: '-', beat: 'The room goes quiet.',
    audio: 'The last note decays. Crickets fade.', focus: 0.5 },
  { id: 'S37', dur: 8.0, ch: 'end', name: 'Credits',
    desc: 'Hand-lettered credits on indigo, the telescope silhouette small at the bottom.',
    cam: 'Locked', chars: '-', beat: '-',
    audio: 'The tune once more, just the first phrase, whistled-sounding.', focus: 0.5 },
];

let _t = 0;
for (const s of SHOTS) { s.start = _t; _t += s.dur; s.end = _t; }
const FILM_DUR = _t;

function shotAt(t) {
  for (const s of SHOTS) if (t < s.end) return s;
  return SHOTS[SHOTS.length - 1];
}
const shotById = id => SHOTS.find(s => s.id === id);

if (typeof module !== 'undefined') module.exports = { SHOTS, FILM_DUR, shotAt, shotById };
